### ISSUE TITLE
사용자 브라우저에서 오류를 감자하여  better ADMIN 화면에서 보여주자.

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#116]
# 배경
* 서버에서 오류나는 경우(예.500 오류) 서버 로그를 통해 확인할 수 있다.
* 사용자 브라우저에서 나는 오류의 경우 감지 하기 어렵다.

# 완료 목표
* 사용자 브라우저에서 나는 오류를 감지하여 better ADMIN 데이터베이스에 저장하고 이를 보여주자.

**Comment by ahnyounghoe** [comment]
이거 내가 추정하는게 맞다면 예전에 대권씨가 개발하던 내용 같은데?

**Comment by YooYoungmo** [comment]
@ahnyounghoe 예 맞습니다.

**Comment by ahnyounghoe** [comment]
@YooYoungmo 혹시 그때 코드도 인수 받았나? 설명을 받거나?

**Comment by ahnyounghoe** [comment]
enhancement 분류가 적절하지 않을 수 있다는 생각이 ...

**Comment by YooYoungmo** [comment]
User Context 와 User Action와 엮어서 digital core 에서 진행하자.
