### ISSUE TITLE
Connected React Router 적용해 보기

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#118]
# 배경
* 현재는 Hash Router를 사용하고 있다.
* [Connected React Router](https://github.com/supasate/connected-react-router)는 Hash Router를 BrowserRouter로 변경해 준다.

# 완료 목표
* 일단 써보고 판단하자.

**Comment by ahnyounghoe** [comment]
기대하는 이점이 뭔가요?

**Comment by YooYoungmo** [comment]
@babokim 이사님이 알려 주신 정보인데요. 무엇인지 정확하게 알지 못해서 써보고 판단할 생각입니다.

**Comment by babokim** [comment]
React를 사용하게 되면 브라우저의 URL이 www.eryuan.co/#/products 와 같이 "#"이 붙게 됩니다. 이것을 hash url 이라고 하는데 검색엔진크롤러는 이 URL을 인식 못합니다. 그리고 사용자 친화적이지도 않고요.
이 솔루션이 내부적으로는 React의 hash url과 동일하게 동작하지만 브라우저에는 일반 url 처럼 나타나게 해주는 것 같습니다.

**Comment by YooYoungmo** [comment]
@babokim 예. 검색 엔진 문제도 있고 
예전에 카카오 앱에서 "#" 이 들어간 URL이 담긴 QR을 찍으면 인식하지 못하는 문제가 있었습니다.

일단 둘다 어드민에서 쓰임새는 아니긴 한데요. 말씀 하셨듯이 사용자 친화적인 문제와
저는 나중에 사용자쪽 페이지 만들 때 써보려고 하는 의도도 있습니다.

**Comment by ahnyounghoe** [comment]
@babokim 설명 고맙습니다. React 가 제공하는 라우터 옵션이네요.
검색해보니 둘 사이 trade-off 설명하는 글이 뜨기도 하네요.
https://wonit.tistory.com/299

**Comment by YooYoungmo** [comment]
@babokim Connected React Router 를 확인해 보니 [리덕스](https://react-redux.js.org/)하고 같이 쓰는거네요.

리덕스는 better admin 사용자의 선택 사항으로 두는게 좋을 것 같습니다.

차리리 HashRouter 를 BrowserRouter로 변경하는게 좋을 것 같습니다.

다만 제약 조건이 있긴 한데요.
BrowserRouter 쓸 때 NGINX 배포 시에 설정 추가 부분이 필요 합니다.
https://romaincauquil.fr/blog/2017/how-to-use-react-router-nginx-docker/

이 문제는 많이 알려진 내용이라서 괜찬을 것 같습니다.
