### ISSUE TITLE
최상단 메뉴 위치를 변경할 수 있게 만든다.

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#128]
# 배경
현재 better ADMIN의 최상단 메뉴는 화면 상단에 위치한다.
![image](https://user-images.githubusercontent.com/16472109/148308977-d62cac5c-1a1f-45c8-bba2-ca8815e3d358.png)

# 완료 목표
Admin 설정에 따라 모든 메뉴가 좌측면에 나타날 수 있도록 만든다.

**Comment by YooYoungmo** [comment]
@torouso  참조 하세요.

**Comment by ahnyounghoe** [comment]
@YooYoungmo 이 작업의 Needs는 어디서 나온 건가요?

**Comment by YooYoungmo** [comment]
@ahnyounghoe 먼저 @babokim 님 예전에 요청하셨습니다.
그리고 @torouso 님도 요청하셨습니다.

메뉴는 사이드로 몰고 최상단 에는 다른 부가 기능(검색 이나 알림 같은)을 넣고 싶다는 욕구입니다.
