### ISSUE TITLE
사용자 접근 로그를 기록하고 보여 준다.

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#134]
# 완료 목표
Admin에 로그인 사용자에 대해 아래 내용을 기록을 남긴다.
* 사용자 ID
* 사용자 IP (어디서 사용 했는지)
* API 호출
* 페이지 이동(URL)

**Comment by ahnyounghoe** [comment]
@gywndi 님도 이 논의를 같이 하고 싶습니다.

**Comment by ahnyounghoe** [comment]
@YooYoungmo 마침 오늘 @gywndi 님을 만나고 왔는데 우리가 통하는데가 있나보군.. :)

**Comment by YooYoungmo** [comment]
@ahnyounghoe 다음 주 쯤 데모가 가능할 것 같습니다 :)
