### ISSUE TITLE
멤버 접근 로그에 API 호출시에는 추가로  응답 HTTP Status Code를 보고 싶다.

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#155]
# 완료 목표
API 호출 시 응답 HTTP Status Code를 수집하고 
아래 화면에 추가로 보여 준다.

![image](https://user-images.githubusercontent.com/16472109/156084805-22e165a0-32f7-4cc7-b9e1-d7739a98941e.png)

**Comment by ahnyounghoe** [comment]
@YooYoungmo 현재 이 화면을 실제로 보고 있거나 볼 예정인 사람이 있을까요?
