### ISSUE TITLE
메뉴 관리를 JSON 파일로만 가능하도록 변경한다.

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#158]
# 배경
기존에 json 파일로 관리되면 메뉴를  #133 으로 DB로 전환했다.

# 문제
* 메뉴를 DB로 관리하다 보니 
   * 배포 환경(개발계, 스테이징, 운영계 등) 마다 데이터를 마이그레이션해 주어야 하는 불편함이 따른다.
* 메뉴 목록 네트워크를 통해 조회하여 가져오다보니
   * 네트워크 특징 상 끊기거나 오류가 날 수 있는데 그러면 화면에서 메뉴가 보이지 않아 아무런 기능도 쓸 수 없다. 

# 완료 목표
메뉴 관리를 DB로 하지 않고 JSON 파일로만 하게 변경한다.

**Comment by ahnyounghoe** [comment]
[주간회의](https://bettercode.dooray.com/project/2828306430874778833/3240691435557360526?order=-createdAt&workflowIds=all&userWorkflowIds=all) 에서 @YooYoungmo 님 얘기를 듣다가 생각난 내용을 씁니다.

네트워크가 끊기면 메뉴도 안 뜬다.
* 캐시가 필요할 수도 있네.
* client-side 에 로딩(저장) 개념이 있으면 좋겠다.
