### ISSUE TITLE
두레이 로그인 시 두레이에서 사용 중인 프로필 이미지 가져와서 better ADMIN에 표시 하기

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#16]

**Comment by YooYoungmo** [comment]
두레이 측에 요청 했으나 응답이 없고, 우선 순위 역시 높지 않아 종료

**Comment by ahnyounghoe** [comment]
@YooYoungmo 두레이 말고 다른 신원 인증 수단을 고려해볼 필요가 있지 않을까요?

**Comment by YooYoungmo** [comment]
@ahnyounghoe https://ko.gravatar.com/ 를 사용할 수 있을 것 같습니다. API가 있어 구현이 가능하다고 판단됩니다.
