### ISSUE TITLE
사이트 설정 > 접근 제어(역할, 권한) 화면을 사이드 메뉴의 설정 메뉴로 옮긴다.

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#191]
# 현재
사이트 설정 > 팝업 방식
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/16472109/196860050-b368ebe2-20aa-4603-a905-4e1dafd7352a.png">

# 목표
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/16472109/196860123-974260d3-a6e7-4db8-a59f-728cf13d7e36.png">

**Comment by ahnyounghoe** [comment]
@YooYoungmo 이걸 반영하고 나면 https://admin.bettercode.kr/ 에서도 접근 제어가 메뉴가 나오는 건가?

**Comment by YooYoungmo** [comment]
@ahnyounghoe 예. 맞습니다. 차차 접근제어 뿐만 아니라 다른 것(사용자/조직도, 로그인 등)도 옮길 예정입니다.
