### ISSUE TITLE
Layout Content 영역이 화면을 영역을 넘어가 확장되는 경우 사이드 바는 확장되지 않는 오류 

### ISSUE THREAD

**Issue by nulLeeKH** [bettercode-oss/better-ADMIN#20]

**Comment by YooYoungmo** [comment]
증상 확인
![image](https://user-images.githubusercontent.com/16472109/116494072-09c2d600-a8db-11eb-9631-c71776f7b07e.png)

**Comment by YooYoungmo** [comment]
@nulLeeKH 버그 리포트 감사합니다. 해당 문제 해결했습니다.
