### ISSUE TITLE
사이트 설정 > 사용자/조직도 화면을 사이드 메뉴의 설정 메뉴로 옮긴다. 

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#200]
# 현재
사이트 설정 > 팝업 방식
![image](https://user-images.githubusercontent.com/16472109/200246645-9c54bf68-edc8-4c99-9d2e-3c5c4eaaafdd.png)

# 완료 목표
사이드 메뉴로 옮긴다.

**Comment by ahnyounghoe** [comment]
@YooYoungmo 현재 조직도 기능을 쓰는 곳이 있나요?

**Comment by YooYoungmo** [comment]
@ahnyounghoe 아름다운 가게 이외에는 없습니다.
