### ISSUE TITLE
개발자가 직접 Icon 컴포넌트를 넣어 메뉴를 구성할 수 있도록 변경한다

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#211]
# 배경
* 현재 메뉴는 navigation.json 파일을 기반으로 만든다.
* 메뉴 icon을 json 파일에 명시할 떄 JSON의 제약으로 Ant Design icon의 이름만(SettingOutlined) 적는다. 아래는 예시
```json
{
  "items": [
    {
      "title": "설정",
      "icon": "SettingOutlined"
    }
  ]
}
```
* 화면에서 메뉴를 Rendering 시 SettingOutlined 의 문자열만 가져와 동적으로 Ant Design Icon Compoent를 로딩하여 화면을 구성한다.

# 문제
* Icon을 Ant Design 에서 제공한 Icon만 사용해야 한다.
* Ant Design 아이콘 수가 적다.
* Ant Design 에 대한 의존성이 크다.
* [React Icons](https://react-icons.github.io/react-icons/) 같은 것을 쓰고 싶다.

# 완료 목표
개발자가 직접 Icon 컴포넌트를 넣어 메뉴를 구성할 수 있도록 변경한다.

**Comment by ahnyounghoe** [comment]
@YooYoungmo SettingOutlined 는 IDE에서 자동완성으로 작성하는 건가? 외워야 하나?

**Comment by YooYoungmo** [comment]
@ahnyounghoe 현재는 아이콘 전체 목록을 확인하기 위해 Ant Design Icon 페이지로 가서 확인 후 
개발자가 직접 입력해야 합니다.
https://ant.design/components/icon

요즘은 Icon 도 React Component 로 제공하는데요.
대표적인 것이 [React Icons](https://react-icons.github.io/react-icons/) 입니다.
아래와 같이 JSON이 아닌 JavaScript로 만들어 개발자가 직접 사용하고 싶은 React Icon Component (Ant Design 이건 React Icon 이건 상관없이)를 
import 하여 사용하게 할 생각입니다.
```javascript
import { FaBeer } from 'react-icons/fa';

export const Navigation = [
   {
      "title": "설정",
      "icon": <FaBeer />
    }
 ];

```
