### ISSUE TITLE
admin 관리페이지 좌즉 같은 메뉴 클릭시 접기 기능 추가

### ISSUE THREAD

**Issue by liche501** [bettercode-oss/better-ADMIN#231]

**Comment by ahnyounghoe** [comment]
@liche501 @YooYoungmo 두 사람의 협업 시도인 듯하여 매우 반갑네요. :)

**Comment by liche501** [comment]
저도 반갑네요~

**Comment by ahnyounghoe** [comment]
@liche501 나중에 Better Admin 에도 커밋을 좀 해.. ㅋㅋㅋ

**Comment by YooYoungmo** [comment]
@liche501 피드백이 늦었습니다. 해당 내용을 아래와 같이 반영 했습니다.
현재 쓰고 있는 Youma에서 쓰고 있는 Better Admin 코드와 GitHub의 코드 베이스가 달라서 @liche501 스스로 수정하기 어려울 것 같은데요.
이 건 따로 소통해서 진행 하시죠.
![better_admin_sider](https://user-images.githubusercontent.com/16472109/209908235-aa359cad-344b-465d-b8a5-9c0f19f6eff3.gif)

**Comment by liche501** [comment]
@YooYoungmo 와우~, 잘 만드셨네요!
저도 코드 확인 했는데 Better Admin 코드와 youma Admin 코드 베이스 가 서로 다르네요 ~
