### ISSUE TITLE
권한 목록 React Component의 테이블 랜더링 조건별 테스트 케이스 작성한다.

### ISSUE THREAD

**Issue by SeulHam** [bettercode-oss/better-ADMIN#271]
# 완료 목표
src/components/templates/access-control/permission/PermissionList.js의 단위 테스트 케이스를 추가한다.

# 제약 조건
테이블 렌더링 조건별 테스트 케이스 작성
1. url parameter 에 따라
2. 권한 유형에 따라
3. pagination에 따라
4. ~~권한 이름 filtering에 따라~~
> [#288 권한 목록 React component의 권한 이름 필터링에 따른 테이블 렌더링 테스트 케이스를 작성한다.](https://github.com/bettercode-oss/better-ADMIN/issues/288)

**Comment by YooYoungmo** [comment]
@SeulHam 이슈 이름을단위 테스트 케이스를 추가한다라고 하기 보다 좀 더 구체적으로 본문에 작성한 것 처럼
`권한 목록 React Component의 테이블 랜더링 조건별 테스트 케이스 작성한다.` 로 하는게 좋을 듯 합니다.
