### ISSUE TITLE
CSS 클래스 중복을 방지하기 위해 CSS Module 사용하기

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#42]

**Comment by YooYoungmo** [comment]
Atomic Design 패턴을 적용하며 [Styled Component](https://styled-components.com/) 를 적용할 예정이므로 이 작업을 대체함.

**Comment by ahnyounghoe** [comment]
@torouso [Styled Component](https://styled-components.com/) 는 차장님도 아시는 건가요?
