### ISSUE TITLE
style 공통 모듈 제작 & JS 파일 내부에 스타일 객체 생성하고 활용하기

### ISSUE THREAD

**Issue by yoonjong-park** [bettercode-oss/better-ADMIN#6]
# 배경
- 일반적으로, style이 통합 관리하는 것이 시각적인 부분의 유지보수에 유리하다.

# 문제
- js 파일의 각 객체마다 style이 구현되어 있다.
- 통합적인 관리가 불가능하다.

#완료 목표
- [ ] 통합적인 관리가 되도록 공통 모듈을 제작한다.
- [ ]  js 파일내부에 style 객체를 생성하고, 공통적인 모듈은 공통 모듈을 적용한다.
- [ ] style 객체를 속성값으로 전달한다.
- [ ] style 객체에 대한 문서화 작업을 진행한다.

**Comment by yoonjong-park** [comment]
@YooYoungmo 이런 스타일로 issue를 작성하면 될까요?

**Comment by YooYoungmo** [comment]
@yoonjong-park 일반적으로 오픈 소스는 이슈 작성을 가이드하는 쪽과 자유롭게 쓰는 쪽이 있습니다.
저는 자유롭게 쓰는 방식을 권합니다. :)

**Comment by ahnyounghoe** [comment]
@yoonjong-park 님도 참여하고 계셨군요. 오픈소스로... 이제야 봤습니다. :)

**Comment by yoonjong-park** [comment]
@YooYoungmo CSS를 inline 방식으로 js 파일 안에 그대로 사용하는 게 그닥 적합하지 않은 것 같은데요.
어떤 방식이 좋을까요?

지금 아름다운가게 admin은 제가 임의로 PostCSS 방식을 채택해서 진행하고 있습니다.

**Comment by YooYoungmo** [comment]
@yoonjong-park 님이 선호하는 방식으로 진행해 주세요.

**Comment by ahnyounghoe** [comment]
> 지금 아름다운가게 admin은 제가 임의로 PostCSS 방식을 채택해서 진행하고 있습니다.

제가 코딩을 안한지 오래되니까 모르는 용어가
@yoonjong-park PostCSS 방식이 뭔가요?

**Comment by yoonjong-park** [comment]
@ahnyounghoe https://yoonjong-park.tistory.com/entry/CSS-PostCSS-%EC%9E%A5%EC%A0%90

**Comment by ahnyounghoe** [comment]
@yoonjong-park 감사. 덕분에 윤종님 블로그도 알게 되네요. ;)

**Comment by YooYoungmo** [comment]
방치된 이슈로 Close 합니다. 필요시 다시 Open 합니다.
