### ISSUE TITLE
wiki images

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#65]

**Comment by YooYoungmo** [comment]
![image](https://user-images.githubusercontent.com/16472109/134877860-f0da057f-cdce-45f1-9b11-32bbb5b5e993.png)

**Comment by ahnyounghoe** [comment]
@YooYoungmo 이름이 wiki images 인 이유는 뭐야?

**Comment by YooYoungmo** [comment]
![스크린샷 2021-09-27 오후 5 57 15](https://user-images.githubusercontent.com/16472109/134878238-693a00cc-0e54-430d-b38c-99e9a41f3ca7.png)

![image](https://user-images.githubusercontent.com/16472109/134878769-4ea128b1-2fc0-4dd5-9b85-69e22e0e0e86.png)

![image](https://user-images.githubusercontent.com/16472109/134879202-87ab821a-f169-4c16-ad18-dcb5fc591682.png)

![image](https://user-images.githubusercontent.com/16472109/134879393-4578c300-cf31-44ab-afda-2f7e2ec4f4af.png)

**Comment by YooYoungmo** [comment]
@ahnyounghoe better ADMIN 사용자 메뉴얼 작업 일부를 GitHub 위키 시작했습니다.

https://github.com/bettercode-oss/better-ADMIN/wiki/%EB%91%90%EB%A0%88%EC%9D%B4-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%84%A4%EC%A0%95-%ED%95%98%EA%B8%B0

그런데 GitHub 위키는 이미지 업로드를 할 수 없는 제약 사항이 있습니다.
그래서 이 이슈는 이미지를 올리는 용도로 쓰고 있습니다.

**Comment by YooYoungmo** [comment]
![better-admin](https://user-images.githubusercontent.com/16472109/204207299-799ee249-2494-4c3a-b572-62a73e276989.png)

**Comment by YooYoungmo** [comment]
![image](https://github.com/bettercode-oss/better-ADMIN/assets/16472109/cfa6ab01-8cd4-45ee-b0c0-31c82555fe50)
![image](https://github.com/bettercode-oss/better-ADMIN/assets/16472109/ee604a21-8d36-48da-ad11-d445460262d7)
![image](https://github.com/bettercode-oss/better-ADMIN/assets/16472109/516fc7c4-cfde-4bca-861a-94b45d95a0f6)
![image](https://github.com/bettercode-oss/better-ADMIN/assets/16472109/85f4fa61-1072-43aa-b813-9e4017ba6b60)
![image](https://github.com/bettercode-oss/better-ADMIN/assets/16472109/6057b36e-d88a-43dd-9b4f-def4ea9bde20)
![image](https://github.com/bettercode-oss/better-ADMIN/assets/16472109/0b9c4137-62f4-4790-8ccd-a7c4779b05a0)
![image](https://github.com/bettercode-oss/better-ADMIN/assets/16472109/0b336343-8ebb-42f6-90b0-e119f4b2a496)
![image](https://github.com/bettercode-oss/better-ADMIN/assets/16472109/7ece84bd-189b-4cbb-9f2e-637b89f063e3)
