### ISSUE TITLE
두레이 로그인 지원

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN#8]
# 완료 목표

https://github.com/bettercode-oss/better-ADMIN/issues/7#issuecomment-808354801 에서 발의된 내용으로
better ADMIN 사이트 설정에 두레이 연결 설정을 하면 두레이 계정으로 로그인할 수 있게 만든다.

**Comment by YooYoungmo** [comment]
두레이 API 문서 
https://helpdesk.dooray.com/share/pages/9wWo-xwiR66BO5LGshgVTg/2937064454837487755

**Comment by ahnyounghoe** [comment]
@YooYoungmo 위 기록은 두레이랑 양쪽에 다 있는거지? Sync(자동복사)되는건 아니고?

**Comment by YooYoungmo** [comment]
@ahnyounghoe 예. 자동 복사 되는 것은 아닙니다.

**Comment by YooYoungmo** [comment]
@ahnyounghoe @yoonjong-park 
아래 처럼 사이트 설정을 통해  `두레이 로그인`을 설정을 할 수 있으며
설정 후에 로그인 화면에 두레이 로그인 버튼이 활성화 됩니다.
![image](https://user-images.githubusercontent.com/16472109/115715978-a6551780-a3b3-11eb-8664-d101d9b70093.png)

![image](https://user-images.githubusercontent.com/16472109/115716011-afde7f80-a3b3-11eb-9da4-888bcabc185d.png)

![image](https://user-images.githubusercontent.com/16472109/115716034-b5d46080-a3b3-11eb-8cc0-7c78112c6a94.png)

**Comment by ahnyounghoe** [comment]
아직 배포는 안된거지?

**Comment by YooYoungmo** [comment]
@ahnyounghoe 예. better ADMIN 을 체험할 수 있는 도메인에 배포는 아직입니다.
